package io.openaffect.flow.domain.joke;

import io.openaffect.flow.domain.IEntity;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Data;
import lombok.Setter;

@Data
@Builder(toBuilder = true)
public class Joke implements IEntity {

  @Setter(AccessLevel.NONE)
  private JokeId id = new JokeId();

  private String author;

  private String text;

  @Setter(AccessLevel.NONE)
  private JokeType jokeType;

  public void categorizeAs(JokeType jokeType) {
    this.jokeType = jokeType;
  }

  // Override the build method generated by Lombok to:
  // - enforce the presence of an id for the entity
  // - assign a default joke type if none is specified
  public static class JokeBuilder {

    public Joke build() {
      if (id == null) {
        id = new JokeId();
      }

      if (text == null) {
        text = "";
      }

      if (jokeType == null) {
        jokeType = JokeType.UNCLASSIFIED;
      }

      if (text.contains("sex")) {
        jokeType = JokeType.ADULT;
      }

      return new Joke(id, author, text, jokeType);
    }

  }
}