# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build and publish Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-          

    - name: Build with Maven
      run: mvn clean package

    - name: Build Docker image (includes mvn clean package)
      run: |
          echo ${{ secrets.OPENAFFECT_PAT }}
          echo ${{ secrets.OPENAFFECT_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker build -t open-affect/flow .
          ./build-image.sh
          docker tag open-affect/flow ghcr.io/openaffect/flow
          docker push ghcr.io/openaffect/flow
        
